project_id = "vxjidpggoemouqrjtkpt"

[functions.genericRelay]
verify_jwt = false

[functions.uploadZipCodes]
verify_jwt = false

[functions.startPass1]
verify_jwt = false

[functions.startPass2]
verify_jwt = false

[functions.saveToVault]
verify_jwt = false
