project_id = "vxjidpggoemouqrjtkpt"

[functions.genericRelay]
verify_jwt = false

[functions.uploadZipCodes]
verify_jwt = false

[functions.startPass1]
verify_jwt = false

[functions.startPass2]
verify_jwt = false

[functions.saveToVault]
verify_jwt = false

[functions.start_pass1]
verify_jwt = false

[functions.start_pass2]
verify_jwt = false

[functions.bulkLoadZips]
verify_jwt = false

[functions.syncZipsFromNeon]
verify_jwt = false
